# Generated by bootstrap.py - commit this file to the repo.
# Each TF layer references it via:
#   terraform init -backend-config=../backend.hcl -backend-config="key=<layer>/terraform.tfstate"

bucket         = "ai-sec-analyst-tfstate-724772086149"
region         = "us-east-2"
dynamodb_table = "ai-sec-analyst-tflocks"
encrypt        = true
kms_key_id     = "arn:aws:kms:us-east-2:724772086149:key/a10d9107-caaa-40da-9466-e188818e5d8b"
